name: less_api_client
version: 0.0.1
description: Flutter/Dart Client of less-api.
homepage: https://www.github.com/Maslow/less-api-client-dart

dependencies:
  dio: ^3.0.10
  
dev_dependencies:
  test: